sonar.projectKey=ms2-turnos-calidad
sonar.projectName=Modulo de turnos - Hospital Central
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.source=21
sonar.java.binaries=build/main
sonar.java.test.binaries=build/test
sonar.java.libraries=lib/deps/*.jar
sonar.java.test.libraries=lib/deps/*.jar
sonar.coverage.jacoco.xmlReportPaths=build/reporte/cobertura.xml
sonar.junit.reportPaths=build/test-reports
sonar.sourceEncoding=UTF-8
